/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "BaseModel.h"

namespace stratis 
{
namespace api 
{

/*
 * BlockHeaderModel
 *
 * 
 */
class STRATISAPI_API BlockHeaderModel : public Model
{
public:
    virtual ~BlockHeaderModel() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<int32> Version;
	TOptional<FString> Merkleroot;
	TOptional<int32> Nonce;
	TOptional<FString> Bits;
	TOptional<FString> Previousblockhash;
	TOptional<int32> Time;
};

}
}
