// Copyright © 2022 Stratis Platform.
//
// This file is part of Stratis Plugin for Unreal Engine. The full copyright notice, including
// terms governing use, modification, and redistribution, is contained in the
// file LICENSE at the root of the source code distribution tree.

/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "BaseModel.h"

namespace stratis {
namespace api {

/*
 * ErrorResult
 *
 *
 */
class STRATISAPI_API ErrorResult : public Model
{
public:
    virtual ~ErrorResult() {}
    bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
    void WriteJson(JsonWriter& Writer) const final;

    TOptional<TSharedPtr<FJsonValue>> Value;
    TOptional<TArray<TSharedPtr<FJsonObject>>> Formatters;
    TOptional<TArray<FString>> ContentTypes;
    TOptional<FString> DeclaredType;
    TOptional<int32> StatusCode;
};

} // namespace api
} // namespace stratis
