/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "BaseModel.h"
#include "UTXOModel.h"

namespace stratis
{
namespace api
{

/*
 * GetUTXOsResponseModel
 *
 * 
 */
class STRATISAPI_API GetUTXOsResponseModel : public Model
{
public:
    virtual ~GetUTXOsResponseModel() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<int64> BalanceSat;
	TOptional<TArray<UTXOModel>> UtxOs;
	TOptional<FString> Reason;
};

}
}
