/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "BaseModel.h"

namespace stratis 
{
namespace api 
{

/*
 * Log
 *
 * 
 */
class STRATISAPI_API Log : public Model
{
public:
    virtual ~Log() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<TArray<uint8>> Address;
	TOptional<TArray<TArray<uint8>>> Topics;
	TOptional<TArray<uint8>> Data;
};

}
}
