/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "BaseModel.h"

namespace stratis
{
namespace api
{

/*
 * ProblemDetails
 *
 * 
 */
class STRATISAPI_API ProblemDetails : public Model
{
public:
    virtual ~ProblemDetails() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<FString> Type;
	TOptional<FString> Title;
	TOptional<int32> Status;
	TOptional<FString> Detail;
	TOptional<FString> Instance;
};

}
}
