// Copyright © 2022 Stratis Platform.
//
// This file is part of Stratis Plugin for Unreal Engine. The full copyright notice, including
// terms governing use, modification, and redistribution, is contained in the
// file LICENSE at the root of the source code distribution tree.

/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "BaseModel.h"
#include "LogResponse.h"

namespace stratis {
namespace api {

/*
 * ReceiptResponse
 *
 *
 */
class STRATISAPI_API ReceiptResponse : public Model
{
public:
    virtual ~ReceiptResponse() {}
    bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
    void WriteJson(JsonWriter& Writer) const final;

    TOptional<FString> TransactionHash;
    TOptional<FString> BlockHash;
    TOptional<int64> BlockNumber;
    TOptional<FString> PostState;
    TOptional<int64> GasUsed;
    TOptional<FString> From;
    TOptional<FString> To;
    TOptional<FString> NewContractAddress;
    TOptional<bool> Success;
    TOptional<FString> ReturnValue;
    TOptional<FString> Bloom;
    TOptional<FString> Error;
    TOptional<TArray<LogResponse>> Logs;
};

} // namespace api
} // namespace stratis
