// Copyright © 2022 Stratis Platform.
//
// This file is part of Stratis Plugin for Unreal Engine. The full copyright notice, including
// terms governing use, modification, and redistribution, is contained in the
// file LICENSE at the root of the source code distribution tree.

/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "BaseModel.h"
#include "UnrealApi.h"

#include "BalanceModel.h"
#include "BlockHeaderModel.h"
#include "BlockModel.h"
#include "GetUTXOsResponseModel.h"
#include "LocalCallContractRequest.h"
#include "LocalExecutionResult.h"
#include "ProblemDetails.h"
#include "RawTxModel.h"
#include "ReceiptResponse.h"
#include "SendTransactionRequest.h"
#include "TipModel.h"
#include "ValidatedAddress.h"

namespace stratis {
namespace api {

/*

*/
class STRATISAPI_API UnrealApi::Unity3dApiUnity3dLocalCallPostRequest
    : public Request
{
public:
    virtual ~Unity3dApiUnity3dLocalCallPostRequest() {}
    void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
    FString ComputePath() const final;

    TOptional<LocalCallContractRequest> LocalCallContractRequest;
};

class STRATISAPI_API UnrealApi::Unity3dApiUnity3dLocalCallPostResponse
    : public Response
{
public:
    virtual ~Unity3dApiUnity3dLocalCallPostResponse() {}
    void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
    bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    LocalExecutionResult Content;
};

/*

*/
class STRATISAPI_API UnrealApi::Unity3dApiUnity3dReceiptGetRequest
    : public Request
{
public:
    virtual ~Unity3dApiUnity3dReceiptGetRequest() {}
    void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
    FString ComputePath() const final;

    TOptional<FString> TxHash;
};

class STRATISAPI_API UnrealApi::Unity3dApiUnity3dReceiptGetResponse
    : public Response
{
public:
    virtual ~Unity3dApiUnity3dReceiptGetResponse() {}
    void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
    bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    ReceiptResponse Content;
};

/*

*/
class STRATISAPI_API UnrealApi::Unity3dBlockGetRequest : public Request
{
public:
    virtual ~Unity3dBlockGetRequest() {}
    void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
    FString ComputePath() const final;

    FString Hash;
    TOptional<bool> ShowTransactionDetails;
    TOptional<bool> OutputJson;
};

class STRATISAPI_API UnrealApi::Unity3dBlockGetResponse : public Response
{
public:
    virtual ~Unity3dBlockGetResponse() {}
    void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
    bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    BlockModel Content;
};

/*

*/
class STRATISAPI_API UnrealApi::Unity3dGetaddressbalanceGetRequest
    : public Request
{
public:
    virtual ~Unity3dGetaddressbalanceGetRequest() {}
    void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
    FString ComputePath() const final;

    TOptional<FString> Address;
};

class STRATISAPI_API UnrealApi::Unity3dGetaddressbalanceGetResponse
    : public Response
{
public:
    virtual ~Unity3dGetaddressbalanceGetResponse() {}
    void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
    bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    BalanceModel Content;
};

/*

*/
class STRATISAPI_API UnrealApi::Unity3dGetblockheaderGetRequest
    : public Request
{
public:
    virtual ~Unity3dGetblockheaderGetRequest() {}
    void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
    FString ComputePath() const final;

    TOptional<FString> Hash;
};

class STRATISAPI_API UnrealApi::Unity3dGetblockheaderGetResponse
    : public Response
{
public:
    virtual ~Unity3dGetblockheaderGetResponse() {}
    void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
    bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    BlockHeaderModel Content;
};

/*

*/
class STRATISAPI_API UnrealApi::Unity3dGetrawtransactionGetRequest
    : public Request
{
public:
    virtual ~Unity3dGetrawtransactionGetRequest() {}
    void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
    FString ComputePath() const final;

    TOptional<FString> Trxid;
};

class STRATISAPI_API UnrealApi::Unity3dGetrawtransactionGetResponse
    : public Response
{
public:
    virtual ~Unity3dGetrawtransactionGetResponse() {}
    void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
    bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    RawTxModel Content;
};

/*

*/
class STRATISAPI_API UnrealApi::Unity3dGetutxosforaddressGetRequest
    : public Request
{
public:
    virtual ~Unity3dGetutxosforaddressGetRequest() {}
    void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
    FString ComputePath() const final;

    TOptional<FString> Address;
};

class STRATISAPI_API UnrealApi::Unity3dGetutxosforaddressGetResponse
    : public Response
{
public:
    virtual ~Unity3dGetutxosforaddressGetResponse() {}
    void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
    bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    GetUTXOsResponseModel Content;
};

/*

*/
class STRATISAPI_API UnrealApi::Unity3dSendTransactionPostRequest
    : public Request
{
public:
    virtual ~Unity3dSendTransactionPostRequest() {}
    void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
    FString ComputePath() const final;

    TOptional<SendTransactionRequest> SendTransactionRequest;
};

class STRATISAPI_API UnrealApi::Unity3dSendTransactionPostResponse
    : public Response
{
public:
    virtual ~Unity3dSendTransactionPostResponse() {}
    void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
    bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
};

/*

*/
class STRATISAPI_API UnrealApi::Unity3dTipGetRequest : public Request
{
public:
    virtual ~Unity3dTipGetRequest() {}
    void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
    FString ComputePath() const final;
};

class STRATISAPI_API UnrealApi::Unity3dTipGetResponse : public Response
{
public:
    virtual ~Unity3dTipGetResponse() {}
    void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
    bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    TipModel Content;
};

/*

*/
class STRATISAPI_API UnrealApi::Unity3dValidateaddressGetRequest
    : public Request
{
public:
    virtual ~Unity3dValidateaddressGetRequest() {}
    void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
    FString ComputePath() const final;

    TOptional<FString> Address;
};

class STRATISAPI_API UnrealApi::Unity3dValidateaddressGetResponse
    : public Response
{
public:
    virtual ~Unity3dValidateaddressGetResponse() {}
    void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
    bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    ValidatedAddress Content;
};

} // namespace api
} // namespace stratis
