// Copyright © 2022 Stratis Platform.
//
// This file is part of Stratis Plugin for Unreal Engine. The full copyright notice, including
// terms governing use, modification, and redistribution, is contained in the
// file LICENSE at the root of the source code distribution tree.

/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "BaseModel.h"
#include "CoreMinimal.h"

namespace stratis {
namespace api {

class STRATISAPI_API UnrealApi
{
public:
    UnrealApi();
    ~UnrealApi();

    /* Sets the URL Endpoint.
     * Note: several fallback endpoints can be configured in request retry policies, see Request::SetShouldRetry */
    void SetURL(const FString& Url);

    /* Adds global header params to all requests */
    void AddHeaderParam(const FString& Key, const FString& Value);
    void ClearHeaderParams();

    /* Sets the retry manager to the user-defined retry manager. User must manage the lifetime of the retry manager.
     * If no retry manager is specified and a request needs retries, a default retry manager will be used.
     * See also: Request::SetShouldRetry */
    void SetHttpRetryManager(FHttpRetrySystem::FManager& RetryManager);
    FHttpRetrySystem::FManager& GetHttpRetryManager();

    class Unity3dBlockGetRequest;
    class Unity3dBlockGetResponse;
    class Unity3dGetAllNftOwnersByContractAddressGetRequest;
    class Unity3dGetAllNftOwnersByContractAddressGetResponse;
    class Unity3dGetOwnedNftsGetRequest;
    class Unity3dGetOwnedNftsGetResponse;
    class Unity3dGetWatchedNftContractsGetRequest;
    class Unity3dGetWatchedNftContractsGetResponse;
    class Unity3dGetaddressbalanceGetRequest;
    class Unity3dGetaddressbalanceGetResponse;
    class Unity3dGetblockheaderGetRequest;
    class Unity3dGetblockheaderGetResponse;
    class Unity3dGetrawtransactionGetRequest;
    class Unity3dGetrawtransactionGetResponse;
    class Unity3dGetutxosforaddressGetRequest;
    class Unity3dGetutxosforaddressGetResponse;
    class Unity3dLocalCallPostRequest;
    class Unity3dLocalCallPostResponse;
    class Unity3dReceiptGetRequest;
    class Unity3dReceiptGetResponse;
    class Unity3dReceiptSearchGetRequest;
    class Unity3dReceiptSearchGetResponse;
    class Unity3dReindexAllContractsGetRequest;
    class Unity3dReindexAllContractsGetResponse;
    class Unity3dSendTransactionPostRequest;
    class Unity3dSendTransactionPostResponse;
    class Unity3dTipGetRequest;
    class Unity3dTipGetResponse;
    class Unity3dUnwatchNftContractGetRequest;
    class Unity3dUnwatchNftContractGetResponse;
    class Unity3dValidateaddressGetRequest;
    class Unity3dValidateaddressGetResponse;
    class Unity3dWatchNftContractGetRequest;
    class Unity3dWatchNftContractGetResponse;
    class Unity3dWatchNftContractsPostRequest;
    class Unity3dWatchNftContractsPostResponse;

    DECLARE_DELEGATE_OneParam(FUnity3dBlockGetDelegate, const Unity3dBlockGetResponse&);
    DECLARE_DELEGATE_OneParam(FUnity3dGetAllNftOwnersByContractAddressGetDelegate, const Unity3dGetAllNftOwnersByContractAddressGetResponse&);
    DECLARE_DELEGATE_OneParam(FUnity3dGetOwnedNftsGetDelegate, const Unity3dGetOwnedNftsGetResponse&);
    DECLARE_DELEGATE_OneParam(FUnity3dGetWatchedNftContractsGetDelegate, const Unity3dGetWatchedNftContractsGetResponse&);
    DECLARE_DELEGATE_OneParam(FUnity3dGetaddressbalanceGetDelegate, const Unity3dGetaddressbalanceGetResponse&);
    DECLARE_DELEGATE_OneParam(FUnity3dGetblockheaderGetDelegate, const Unity3dGetblockheaderGetResponse&);
    DECLARE_DELEGATE_OneParam(FUnity3dGetrawtransactionGetDelegate, const Unity3dGetrawtransactionGetResponse&);
    DECLARE_DELEGATE_OneParam(FUnity3dGetutxosforaddressGetDelegate, const Unity3dGetutxosforaddressGetResponse&);
    DECLARE_DELEGATE_OneParam(FUnity3dLocalCallPostDelegate, const Unity3dLocalCallPostResponse&);
    DECLARE_DELEGATE_OneParam(FUnity3dReceiptGetDelegate, const Unity3dReceiptGetResponse&);
    DECLARE_DELEGATE_OneParam(FUnity3dReceiptSearchGetDelegate, const Unity3dReceiptSearchGetResponse&);
    DECLARE_DELEGATE_OneParam(FUnity3dReindexAllContractsGetDelegate, const Unity3dReindexAllContractsGetResponse&);
    DECLARE_DELEGATE_OneParam(FUnity3dSendTransactionPostDelegate, const Unity3dSendTransactionPostResponse&);
    DECLARE_DELEGATE_OneParam(FUnity3dTipGetDelegate, const Unity3dTipGetResponse&);
    DECLARE_DELEGATE_OneParam(FUnity3dUnwatchNftContractGetDelegate, const Unity3dUnwatchNftContractGetResponse&);
    DECLARE_DELEGATE_OneParam(FUnity3dValidateaddressGetDelegate, const Unity3dValidateaddressGetResponse&);
    DECLARE_DELEGATE_OneParam(FUnity3dWatchNftContractGetDelegate, const Unity3dWatchNftContractGetResponse&);
    DECLARE_DELEGATE_OneParam(FUnity3dWatchNftContractsPostDelegate, const Unity3dWatchNftContractsPostResponse&);

    FHttpRequestPtr Unity3dBlockGet(const Unity3dBlockGetRequest& Request, const FUnity3dBlockGetDelegate& Delegate = FUnity3dBlockGetDelegate()) const;
    FHttpRequestPtr Unity3dGetAllNftOwnersByContractAddressGet(const Unity3dGetAllNftOwnersByContractAddressGetRequest& Request, const FUnity3dGetAllNftOwnersByContractAddressGetDelegate& Delegate = FUnity3dGetAllNftOwnersByContractAddressGetDelegate()) const;
    FHttpRequestPtr Unity3dGetOwnedNftsGet(const Unity3dGetOwnedNftsGetRequest& Request, const FUnity3dGetOwnedNftsGetDelegate& Delegate = FUnity3dGetOwnedNftsGetDelegate()) const;
    FHttpRequestPtr Unity3dGetWatchedNftContractsGet(const Unity3dGetWatchedNftContractsGetRequest& Request, const FUnity3dGetWatchedNftContractsGetDelegate& Delegate = FUnity3dGetWatchedNftContractsGetDelegate()) const;
    FHttpRequestPtr Unity3dGetaddressbalanceGet(const Unity3dGetaddressbalanceGetRequest& Request, const FUnity3dGetaddressbalanceGetDelegate& Delegate = FUnity3dGetaddressbalanceGetDelegate()) const;
    FHttpRequestPtr Unity3dGetblockheaderGet(const Unity3dGetblockheaderGetRequest& Request, const FUnity3dGetblockheaderGetDelegate& Delegate = FUnity3dGetblockheaderGetDelegate()) const;
    FHttpRequestPtr Unity3dGetrawtransactionGet(const Unity3dGetrawtransactionGetRequest& Request, const FUnity3dGetrawtransactionGetDelegate& Delegate = FUnity3dGetrawtransactionGetDelegate()) const;
    FHttpRequestPtr Unity3dGetutxosforaddressGet(const Unity3dGetutxosforaddressGetRequest& Request, const FUnity3dGetutxosforaddressGetDelegate& Delegate = FUnity3dGetutxosforaddressGetDelegate()) const;
    FHttpRequestPtr Unity3dLocalCallPost(const Unity3dLocalCallPostRequest& Request, const FUnity3dLocalCallPostDelegate& Delegate = FUnity3dLocalCallPostDelegate()) const;
    FHttpRequestPtr Unity3dReceiptGet(const Unity3dReceiptGetRequest& Request, const FUnity3dReceiptGetDelegate& Delegate = FUnity3dReceiptGetDelegate()) const;
    FHttpRequestPtr Unity3dReceiptSearchGet(const Unity3dReceiptSearchGetRequest& Request, const FUnity3dReceiptSearchGetDelegate& Delegate = FUnity3dReceiptSearchGetDelegate()) const;
    FHttpRequestPtr Unity3dReindexAllContractsGet(const Unity3dReindexAllContractsGetRequest& Request, const FUnity3dReindexAllContractsGetDelegate& Delegate = FUnity3dReindexAllContractsGetDelegate()) const;
    FHttpRequestPtr Unity3dSendTransactionPost(const Unity3dSendTransactionPostRequest& Request, const FUnity3dSendTransactionPostDelegate& Delegate = FUnity3dSendTransactionPostDelegate()) const;
    FHttpRequestPtr Unity3dTipGet(const Unity3dTipGetRequest& Request, const FUnity3dTipGetDelegate& Delegate = FUnity3dTipGetDelegate()) const;
    FHttpRequestPtr Unity3dUnwatchNftContractGet(const Unity3dUnwatchNftContractGetRequest& Request, const FUnity3dUnwatchNftContractGetDelegate& Delegate = FUnity3dUnwatchNftContractGetDelegate()) const;
    FHttpRequestPtr Unity3dValidateaddressGet(const Unity3dValidateaddressGetRequest& Request, const FUnity3dValidateaddressGetDelegate& Delegate = FUnity3dValidateaddressGetDelegate()) const;
    FHttpRequestPtr Unity3dWatchNftContractGet(const Unity3dWatchNftContractGetRequest& Request, const FUnity3dWatchNftContractGetDelegate& Delegate = FUnity3dWatchNftContractGetDelegate()) const;
    FHttpRequestPtr Unity3dWatchNftContractsPost(const Unity3dWatchNftContractsPostRequest& Request, const FUnity3dWatchNftContractsPostDelegate& Delegate = FUnity3dWatchNftContractsPostDelegate()) const;

private:
    void OnUnity3dBlockGetResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUnity3dBlockGetDelegate Delegate) const;
    void OnUnity3dGetAllNftOwnersByContractAddressGetResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUnity3dGetAllNftOwnersByContractAddressGetDelegate Delegate) const;
    void OnUnity3dGetOwnedNftsGetResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUnity3dGetOwnedNftsGetDelegate Delegate) const;
    void OnUnity3dGetWatchedNftContractsGetResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUnity3dGetWatchedNftContractsGetDelegate Delegate) const;
    void OnUnity3dGetaddressbalanceGetResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUnity3dGetaddressbalanceGetDelegate Delegate) const;
    void OnUnity3dGetblockheaderGetResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUnity3dGetblockheaderGetDelegate Delegate) const;
    void OnUnity3dGetrawtransactionGetResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUnity3dGetrawtransactionGetDelegate Delegate) const;
    void OnUnity3dGetutxosforaddressGetResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUnity3dGetutxosforaddressGetDelegate Delegate) const;
    void OnUnity3dLocalCallPostResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUnity3dLocalCallPostDelegate Delegate) const;
    void OnUnity3dReceiptGetResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUnity3dReceiptGetDelegate Delegate) const;
    void OnUnity3dReceiptSearchGetResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUnity3dReceiptSearchGetDelegate Delegate) const;
    void OnUnity3dReindexAllContractsGetResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUnity3dReindexAllContractsGetDelegate Delegate) const;
    void OnUnity3dSendTransactionPostResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUnity3dSendTransactionPostDelegate Delegate) const;
    void OnUnity3dTipGetResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUnity3dTipGetDelegate Delegate) const;
    void OnUnity3dUnwatchNftContractGetResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUnity3dUnwatchNftContractGetDelegate Delegate) const;
    void OnUnity3dValidateaddressGetResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUnity3dValidateaddressGetDelegate Delegate) const;
    void OnUnity3dWatchNftContractGetResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUnity3dWatchNftContractGetDelegate Delegate) const;
    void OnUnity3dWatchNftContractsPostResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUnity3dWatchNftContractsPostDelegate Delegate) const;

    FHttpRequestRef CreateHttpRequest(const Request& Request) const;
    bool IsValid() const;
    void HandleResponse(FHttpResponsePtr HttpResponse, bool bSucceeded, Response& InOutResponse) const;

    FString Url;
    TMap<FString, FString> AdditionalHeaderParams;
    mutable FHttpRetrySystem::FManager* RetryManager = nullptr;
    mutable TUniquePtr<HttpRetryManager> DefaultRetryManager;
};

} // namespace api
} // namespace stratis
