/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "CoreMinimal.h"
#include "BaseModel.h"

namespace stratis
{
namespace api
{

class STRATISAPI_API UnrealApi
{
public:
	UnrealApi();
	~UnrealApi();

	/* Sets the URL Endpoint.
	* Note: several fallback endpoints can be configured in request retry policies, see Request::SetShouldRetry */
	void SetURL(const FString& Url);

	/* Adds global header params to all requests */
	void AddHeaderParam(const FString& Key, const FString& Value);
	void ClearHeaderParams();

	/* Sets the retry manager to the user-defined retry manager. User must manage the lifetime of the retry manager.
	* If no retry manager is specified and a request needs retries, a default retry manager will be used.
	* See also: Request::SetShouldRetry */
	void SetHttpRetryManager(FHttpRetrySystem::FManager& RetryManager);
	FHttpRetrySystem::FManager& GetHttpRetryManager();

	class Unity3dApiUnity3dLocalCallPostRequest;
	class Unity3dApiUnity3dLocalCallPostResponse;
	class Unity3dApiUnity3dReceiptGetRequest;
	class Unity3dApiUnity3dReceiptGetResponse;
	class Unity3dBlockGetRequest;
	class Unity3dBlockGetResponse;
	class Unity3dGetaddressbalanceGetRequest;
	class Unity3dGetaddressbalanceGetResponse;
	class Unity3dGetblockheaderGetRequest;
	class Unity3dGetblockheaderGetResponse;
	class Unity3dGetrawtransactionGetRequest;
	class Unity3dGetrawtransactionGetResponse;
	class Unity3dGetutxosforaddressGetRequest;
	class Unity3dGetutxosforaddressGetResponse;
	class Unity3dSendTransactionPostRequest;
	class Unity3dSendTransactionPostResponse;
	class Unity3dTipGetRequest;
	class Unity3dTipGetResponse;
	class Unity3dValidateaddressGetRequest;
	class Unity3dValidateaddressGetResponse;
	
    DECLARE_DELEGATE_OneParam(FUnity3dApiUnity3dLocalCallPostDelegate, const Unity3dApiUnity3dLocalCallPostResponse&);
    DECLARE_DELEGATE_OneParam(FUnity3dApiUnity3dReceiptGetDelegate, const Unity3dApiUnity3dReceiptGetResponse&);
    DECLARE_DELEGATE_OneParam(FUnity3dBlockGetDelegate, const Unity3dBlockGetResponse&);
    DECLARE_DELEGATE_OneParam(FUnity3dGetaddressbalanceGetDelegate, const Unity3dGetaddressbalanceGetResponse&);
    DECLARE_DELEGATE_OneParam(FUnity3dGetblockheaderGetDelegate, const Unity3dGetblockheaderGetResponse&);
    DECLARE_DELEGATE_OneParam(FUnity3dGetrawtransactionGetDelegate, const Unity3dGetrawtransactionGetResponse&);
    DECLARE_DELEGATE_OneParam(FUnity3dGetutxosforaddressGetDelegate, const Unity3dGetutxosforaddressGetResponse&);
    DECLARE_DELEGATE_OneParam(FUnity3dSendTransactionPostDelegate, const Unity3dSendTransactionPostResponse&);
    DECLARE_DELEGATE_OneParam(FUnity3dTipGetDelegate, const Unity3dTipGetResponse&);
    DECLARE_DELEGATE_OneParam(FUnity3dValidateaddressGetDelegate, const Unity3dValidateaddressGetResponse&);
    
    FHttpRequestPtr Unity3dApiUnity3dLocalCallPost(const Unity3dApiUnity3dLocalCallPostRequest& Request, const FUnity3dApiUnity3dLocalCallPostDelegate& Delegate = FUnity3dApiUnity3dLocalCallPostDelegate()) const;
    FHttpRequestPtr Unity3dApiUnity3dReceiptGet(const Unity3dApiUnity3dReceiptGetRequest& Request, const FUnity3dApiUnity3dReceiptGetDelegate& Delegate = FUnity3dApiUnity3dReceiptGetDelegate()) const;
    FHttpRequestPtr Unity3dBlockGet(const Unity3dBlockGetRequest& Request, const FUnity3dBlockGetDelegate& Delegate = FUnity3dBlockGetDelegate()) const;
    FHttpRequestPtr Unity3dGetaddressbalanceGet(const Unity3dGetaddressbalanceGetRequest& Request, const FUnity3dGetaddressbalanceGetDelegate& Delegate = FUnity3dGetaddressbalanceGetDelegate()) const;
    FHttpRequestPtr Unity3dGetblockheaderGet(const Unity3dGetblockheaderGetRequest& Request, const FUnity3dGetblockheaderGetDelegate& Delegate = FUnity3dGetblockheaderGetDelegate()) const;
    FHttpRequestPtr Unity3dGetrawtransactionGet(const Unity3dGetrawtransactionGetRequest& Request, const FUnity3dGetrawtransactionGetDelegate& Delegate = FUnity3dGetrawtransactionGetDelegate()) const;
    FHttpRequestPtr Unity3dGetutxosforaddressGet(const Unity3dGetutxosforaddressGetRequest& Request, const FUnity3dGetutxosforaddressGetDelegate& Delegate = FUnity3dGetutxosforaddressGetDelegate()) const;
    FHttpRequestPtr Unity3dSendTransactionPost(const Unity3dSendTransactionPostRequest& Request, const FUnity3dSendTransactionPostDelegate& Delegate = FUnity3dSendTransactionPostDelegate()) const;
    FHttpRequestPtr Unity3dTipGet(const Unity3dTipGetRequest& Request, const FUnity3dTipGetDelegate& Delegate = FUnity3dTipGetDelegate()) const;
    FHttpRequestPtr Unity3dValidateaddressGet(const Unity3dValidateaddressGetRequest& Request, const FUnity3dValidateaddressGetDelegate& Delegate = FUnity3dValidateaddressGetDelegate()) const;
    
private:
    void OnUnity3dApiUnity3dLocalCallPostResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUnity3dApiUnity3dLocalCallPostDelegate Delegate) const;
    void OnUnity3dApiUnity3dReceiptGetResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUnity3dApiUnity3dReceiptGetDelegate Delegate) const;
    void OnUnity3dBlockGetResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUnity3dBlockGetDelegate Delegate) const;
    void OnUnity3dGetaddressbalanceGetResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUnity3dGetaddressbalanceGetDelegate Delegate) const;
    void OnUnity3dGetblockheaderGetResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUnity3dGetblockheaderGetDelegate Delegate) const;
    void OnUnity3dGetrawtransactionGetResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUnity3dGetrawtransactionGetDelegate Delegate) const;
    void OnUnity3dGetutxosforaddressGetResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUnity3dGetutxosforaddressGetDelegate Delegate) const;
    void OnUnity3dSendTransactionPostResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUnity3dSendTransactionPostDelegate Delegate) const;
    void OnUnity3dTipGetResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUnity3dTipGetDelegate Delegate) const;
    void OnUnity3dValidateaddressGetResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUnity3dValidateaddressGetDelegate Delegate) const;
    
	FHttpRequestRef CreateHttpRequest(const Request& Request) const;
	bool IsValid() const;
	void HandleResponse(FHttpResponsePtr HttpResponse, bool bSucceeded, Response& InOutResponse) const;

	FString Url;
	TMap<FString,FString> AdditionalHeaderParams;
	mutable FHttpRetrySystem::FManager* RetryManager = nullptr;
	mutable TUniquePtr<HttpRetryManager> DefaultRetryManager;
};

}
}
