/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "BalanceModel.h"

#include "Helpers.h"
#include "StratisAPIModule.h"

#include "Templates/SharedPointer.h"

namespace stratis {
namespace api {

void BalanceModel::WriteJson(JsonWriter &Writer) const {
  Writer->WriteObjectStart();
  Writer->WriteIdentifierPrefix(TEXT("balance"));
  WriteJsonValue(Writer, Balance.GetValue());
  Writer->WriteObjectEnd();
}

bool BalanceModel::FromJson(const TSharedPtr<FJsonValue> &JsonValue) {
  const TSharedPtr<FJsonObject> *Object;
  if (!JsonValue->TryGetObject(Object))
    return false;

  bool ParseSuccess = true;

  ParseSuccess &= TryGetJsonValue(*Object, TEXT("balance"), Balance);

  return ParseSuccess;
}

} // namespace api
} // namespace stratis
