// Copyright © 2022 Stratis Platform.
//
// This file is part of Stratis Plugin for Unreal Engine. The full copyright notice, including
// terms governing use, modification, and redistribution, is contained in the
// file LICENSE at the root of the source code distribution tree.

/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "BlockHeaderModel.h"

#include "Helpers.h"
#include "StratisAPIModule.h"

#include "Templates/SharedPointer.h"

namespace stratis {
namespace api {

void BlockHeaderModel::WriteJson(JsonWriter& Writer) const
{
    Writer->WriteObjectStart();
    if (Version.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("version"));
        WriteJsonValue(Writer, Version.GetValue());
    }
    if (Merkleroot.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("merkleroot"));
        WriteJsonValue(Writer, Merkleroot.GetValue());
    }
    if (Nonce.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("nonce"));
        WriteJsonValue(Writer, Nonce.GetValue());
    }
    if (Bits.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("bits"));
        WriteJsonValue(Writer, Bits.GetValue());
    }
    if (Previousblockhash.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("previousblockhash"));
        WriteJsonValue(Writer, Previousblockhash.GetValue());
    }
    if (Time.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("time"));
        WriteJsonValue(Writer, Time.GetValue());
    }
    Writer->WriteObjectEnd();
}

bool BlockHeaderModel::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
    const TSharedPtr<FJsonObject>* Object;
    if (!JsonValue->TryGetObject(Object))
        return false;

    bool ParseSuccess = true;

    ParseSuccess &= TryGetJsonValue(*Object, TEXT("version"), Version);
    ParseSuccess &= TryGetJsonValue(*Object, TEXT("merkleroot"), Merkleroot);
    ParseSuccess &= TryGetJsonValue(*Object, TEXT("nonce"), Nonce);
    ParseSuccess &= TryGetJsonValue(*Object, TEXT("bits"), Bits);
    ParseSuccess &= TryGetJsonValue(*Object, TEXT("previousblockhash"), Previousblockhash);
    ParseSuccess &= TryGetJsonValue(*Object, TEXT("time"), Time);

    return ParseSuccess;
}

} // namespace api
} // namespace stratis
