// Copyright © 2022 Stratis Platform.
//
// This file is part of Stratis Plugin for Unreal Engine. The full copyright notice, including
// terms governing use, modification, and redistribution, is contained in the
// file LICENSE at the root of the source code distribution tree.

/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "ErrorResult.h"

#include "Helpers.h"
#include "StratisAPIModule.h"

#include "Templates/SharedPointer.h"

namespace stratis {
namespace api {

void ErrorResult::WriteJson(JsonWriter& Writer) const
{
    Writer->WriteObjectStart();
    if (Value.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("Value"));
        WriteJsonValue(Writer, Value.GetValue());
    }
    if (Formatters.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("Formatters"));
        WriteJsonValue(Writer, Formatters.GetValue());
    }
    if (ContentTypes.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("ContentTypes"));
        WriteJsonValue(Writer, ContentTypes.GetValue());
    }
    if (DeclaredType.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("DeclaredType"));
        WriteJsonValue(Writer, DeclaredType.GetValue());
    }
    if (StatusCode.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("StatusCode"));
        WriteJsonValue(Writer, StatusCode.GetValue());
    }
    Writer->WriteObjectEnd();
}

bool ErrorResult::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
    const TSharedPtr<FJsonObject>* Object;
    if (!JsonValue->TryGetObject(Object))
        return false;

    bool ParseSuccess = true;

    ParseSuccess &= TryGetJsonValue(*Object, TEXT("Value"), Value);
    ParseSuccess &= TryGetJsonValue(*Object, TEXT("Formatters"), Formatters);
    ParseSuccess &= TryGetJsonValue(*Object, TEXT("ContentTypes"), ContentTypes);
    ParseSuccess &= TryGetJsonValue(*Object, TEXT("DeclaredType"), DeclaredType);
    ParseSuccess &= TryGetJsonValue(*Object, TEXT("StatusCode"), StatusCode);

    return ParseSuccess;
}

} // namespace api
} // namespace stratis
