// Copyright © 2022 Stratis Platform.
//
// This file is part of Stratis Plugin for Unreal Engine. The full copyright notice, including
// terms governing use, modification, and redistribution, is contained in the
// file LICENSE at the root of the source code distribution tree.

/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "GetUTXOsResponseModel.h"

#include "StratisAPIModule.h"
#include "Helpers.h"

#include "Templates/SharedPointer.h"

namespace stratis
{
namespace api
{

void GetUTXOsResponseModel::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (BalanceSat.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("balanceSat")); WriteJsonValue(Writer, BalanceSat.GetValue());
	}
	if (UtxOs.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("utxOs")); WriteJsonValue(Writer, UtxOs.GetValue());
	}
	if (Reason.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("reason")); WriteJsonValue(Writer, Reason.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool GetUTXOsResponseModel::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("balanceSat"), BalanceSat);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("utxOs"), UtxOs);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("reason"), Reason);

	return ParseSuccess;
}

}
}
