// Copyright © 2022 Stratis Platform.
//
// This file is part of Stratis Plugin for Unreal Engine. The full copyright notice, including
// terms governing use, modification, and redistribution, is contained in the
// file LICENSE at the root of the source code distribution tree.

/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "LocalCallContractRequest.h"

#include "Helpers.h"
#include "StratisAPIModule.h"

#include "Templates/SharedPointer.h"

namespace stratis {
namespace api {

void LocalCallContractRequest::WriteJson(JsonWriter& Writer) const
{
    Writer->WriteObjectStart();
    if (BlockHeight.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("BlockHeight"));
        WriteJsonValue(Writer, BlockHeight.GetValue());
    }
    Writer->WriteIdentifierPrefix(TEXT("ContractAddress"));
    WriteJsonValue(Writer, ContractAddress);
    Writer->WriteIdentifierPrefix(TEXT("MethodName"));
    WriteJsonValue(Writer, MethodName);
    if (Amount.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("Amount"));
        WriteJsonValue(Writer, Amount.GetValue());
    }
    if (GasPrice.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("GasPrice"));
        WriteJsonValue(Writer, GasPrice.GetValue());
    }
    if (GasLimit.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("GasLimit"));
        WriteJsonValue(Writer, GasLimit.GetValue());
    }
    if (Sender.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("Sender"));
        WriteJsonValue(Writer, Sender.GetValue());
    }
    if (Parameters.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("Parameters"));
        WriteJsonValue(Writer, Parameters.GetValue());
    }
    Writer->WriteObjectEnd();
}

bool LocalCallContractRequest::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
    const TSharedPtr<FJsonObject>* Object;
    if (!JsonValue->TryGetObject(Object))
        return false;

    bool ParseSuccess = true;

    ParseSuccess &= TryGetJsonValue(*Object, TEXT("BlockHeight"), BlockHeight);
    ParseSuccess &= TryGetJsonValue(*Object, TEXT("ContractAddress"), ContractAddress);
    ParseSuccess &= TryGetJsonValue(*Object, TEXT("MethodName"), MethodName);
    ParseSuccess &= TryGetJsonValue(*Object, TEXT("Amount"), Amount);
    ParseSuccess &= TryGetJsonValue(*Object, TEXT("GasPrice"), GasPrice);
    ParseSuccess &= TryGetJsonValue(*Object, TEXT("GasLimit"), GasLimit);
    ParseSuccess &= TryGetJsonValue(*Object, TEXT("Sender"), Sender);
    ParseSuccess &= TryGetJsonValue(*Object, TEXT("Parameters"), Parameters);

    return ParseSuccess;
}

} // namespace api
} // namespace stratis
