// Copyright © 2022 Stratis Platform.
//
// This file is part of Stratis Plugin for Unreal Engine. The full copyright notice, including
// terms governing use, modification, and redistribution, is contained in the
// file LICENSE at the root of the source code distribution tree.

/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "LogResponse.h"

#include "Helpers.h"
#include "StratisAPIModule.h"

#include "Templates/SharedPointer.h"

namespace stratis {
namespace api {

void LogResponse::WriteJson(JsonWriter& Writer) const
{
    Writer->WriteObjectStart();
    if (Address.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("address"));
        WriteJsonValue(Writer, Address.GetValue());
    }
    if (Topics.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("topics"));
        WriteJsonValue(Writer, Topics.GetValue());
    }
    if (Data.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("data"));
        WriteJsonValue(Writer, Data.GetValue());
    }
    if (Log.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("log"));
        WriteJsonValue(Writer, Log.GetValue());
    }
    Writer->WriteObjectEnd();
}

bool LogResponse::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
    const TSharedPtr<FJsonObject>* Object;
    if (!JsonValue->TryGetObject(Object))
        return false;

    bool ParseSuccess = true;

    ParseSuccess &= TryGetJsonValue(*Object, TEXT("address"), Address);
    ParseSuccess &= TryGetJsonValue(*Object, TEXT("topics"), Topics);
    ParseSuccess &= TryGetJsonValue(*Object, TEXT("data"), Data);
    ParseSuccess &= TryGetJsonValue(*Object, TEXT("log"), Log);

    return ParseSuccess;
}

} // namespace api
} // namespace stratis
