// Copyright © 2022 Stratis Platform.
//
// This file is part of Stratis Plugin for Unreal Engine. The full copyright notice, including
// terms governing use, modification, and redistribution, is contained in the
// file LICENSE at the root of the source code distribution tree.

/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "NFTContractModel.h"

#include "Helpers.h"
#include "StratisAPIModule.h"

#include "Templates/SharedPointer.h"

namespace stratis {
namespace api {

void NFTContractModel::WriteJson(JsonWriter& Writer) const
{
    Writer->WriteObjectStart();
    if (Id.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("Id"));
        WriteJsonValue(Writer, Id.GetValue());
    }
    if (ContractAddress.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("ContractAddress"));
        WriteJsonValue(Writer, ContractAddress.GetValue());
    }
    if (OwnedIDsByAddress.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("OwnedIDsByAddress"));
        WriteJsonValue(Writer, OwnedIDsByAddress.GetValue());
    }
    if (LastUpdatedBlock.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("LastUpdatedBlock"));
        WriteJsonValue(Writer, LastUpdatedBlock.GetValue());
    }
    Writer->WriteObjectEnd();
}

bool NFTContractModel::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
    const TSharedPtr<FJsonObject>* Object;
    if (!JsonValue->TryGetObject(Object))
        return false;

    bool ParseSuccess = true;

    ParseSuccess &= TryGetJsonValue(*Object, TEXT("Id"), Id);
    ParseSuccess &= TryGetJsonValue(*Object, TEXT("ContractAddress"), ContractAddress);
    ParseSuccess &= TryGetJsonValue(*Object, TEXT("OwnedIDsByAddress"), OwnedIDsByAddress);
    ParseSuccess &= TryGetJsonValue(*Object, TEXT("LastUpdatedBlock"), LastUpdatedBlock);

    return ParseSuccess;
}

} // namespace api
} // namespace stratis
