// Copyright © 2022 Stratis Platform.
//
// This file is part of Stratis Plugin for Unreal Engine. The full copyright notice, including
// terms governing use, modification, and redistribution, is contained in the
// file LICENSE at the root of the source code distribution tree.

/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "ProblemDetails.h"

#include "Helpers.h"
#include "StratisAPIModule.h"

#include "Templates/SharedPointer.h"

namespace stratis {
namespace api {

void ProblemDetails::WriteJson(JsonWriter& Writer) const
{
    Writer->WriteObjectStart();
    if (Type.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("Type"));
        WriteJsonValue(Writer, Type.GetValue());
    }
    if (Title.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("Title"));
        WriteJsonValue(Writer, Title.GetValue());
    }
    if (Status.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("Status"));
        WriteJsonValue(Writer, Status.GetValue());
    }
    if (Detail.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("Detail"));
        WriteJsonValue(Writer, Detail.GetValue());
    }
    if (Instance.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("Instance"));
        WriteJsonValue(Writer, Instance.GetValue());
    }
    Writer->WriteObjectEnd();
}

bool ProblemDetails::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
    const TSharedPtr<FJsonObject>* Object;
    if (!JsonValue->TryGetObject(Object))
        return false;

    bool ParseSuccess = true;

    ParseSuccess &= TryGetJsonValue(*Object, TEXT("Type"), Type);
    ParseSuccess &= TryGetJsonValue(*Object, TEXT("Title"), Title);
    ParseSuccess &= TryGetJsonValue(*Object, TEXT("Status"), Status);
    ParseSuccess &= TryGetJsonValue(*Object, TEXT("Detail"), Detail);
    ParseSuccess &= TryGetJsonValue(*Object, TEXT("Instance"), Instance);

    return ParseSuccess;
}

} // namespace api
} // namespace stratis
