// Copyright © 2022 Stratis Platform.
//
// This file is part of Stratis Plugin for Unreal Engine. The full copyright notice, including
// terms governing use, modification, and redistribution, is contained in the
// file LICENSE at the root of the source code distribution tree.

/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "StratisAPIModule.h"

IMPLEMENT_MODULE(StratisAPIModule, StratisAPI);
DEFINE_LOG_CATEGORY(LogStratisAPI);

void StratisAPIModule::StartupModule()
{
}

void StratisAPIModule::ShutdownModule()
{
}
