// Copyright © 2022 Stratis Platform.
//
// This file is part of Stratis Plugin for Unreal Engine. The full copyright notice, including
// terms governing use, modification, and redistribution, is contained in the
// file LICENSE at the root of the source code distribution tree.

/**
 * Stratis Node API
 * Access to the Stratis Node's api.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "TransactionOutputModel.h"

#include "Helpers.h"
#include "StratisAPIModule.h"

#include "Templates/SharedPointer.h"

namespace stratis {
namespace api {

void TransactionOutputModel::WriteJson(JsonWriter& Writer) const
{
    Writer->WriteObjectStart();
    if (Address.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("address"));
        WriteJsonValue(Writer, Address.GetValue());
    }
    if (Amount.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("amount"));
        WriteJsonValue(Writer, Amount.GetValue());
    }
    if (OpReturnData.IsSet()) {
        Writer->WriteIdentifierPrefix(TEXT("opReturnData"));
        WriteJsonValue(Writer, OpReturnData.GetValue());
    }
    Writer->WriteObjectEnd();
}

bool TransactionOutputModel::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
    const TSharedPtr<FJsonObject>* Object;
    if (!JsonValue->TryGetObject(Object))
        return false;

    bool ParseSuccess = true;

    ParseSuccess &= TryGetJsonValue(*Object, TEXT("address"), Address);
    ParseSuccess &= TryGetJsonValue(*Object, TEXT("amount"), Amount);
    ParseSuccess &= TryGetJsonValue(*Object, TEXT("opReturnData"), OpReturnData);

    return ParseSuccess;
}

} // namespace api
} // namespace stratis
